# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<SCRIPT
echo "Installing vagrant..."
sudo yum -y install vagrant
echo "done!"

echo "Installing Docker..."
sudo yum -y install docker-io
sudo echo "other_args=\\\"--insecure-registry <PRIVATE_DOCKERHUB_FQDN>\\\"" > /etc/sysconfig/docker
sudo service docker start
echo "done!"

echo "Grant docker access right to vagrant user"
sudo usermod -a -G docker vagrant

echo "Closing iptables..."
service iptables stop
chkconfig iptables off
SCRIPT

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.synced_folder '../../../hadoocker', '/hadoocker'

  config.vm.box_download_insecure = true
  config.vm.box = "centos6"

  # If you're using laptop and WIFI network, mark out public_network since it can not obtain the DHCP IP.
  # The public_network works fine with wired network only in our environment.
  config.vm.network "public_network"
  config.vm.provision "shell", inline: $script
  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--memory", "2048"]
  end
end
