# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<SCRIPT
echo "Installing vagrant..."
sudo yum -y install vagrant
echo "done!"

echo "Installing Docker..."
sudo yum -y install docker-io
sudo echo "other_args=\\\"--insecure-registry <PRIVATE_DOCKERHUB_FQDN>\\\"" > /etc/sysconfig/docker
sudo service docker start
echo "done!"

echo "Closing iptables..."
service iptables stop
chkconfig iptables off
SCRIPT

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "hadoocker-base-centos6"
  config.vm.box_url = "evansye/hadoocker-base"

  config.vm.network "public_network"
  config.vm.provision "shell", inline: $script
  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--memory", "2048"]
  end
end
