# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "bigtop-centos6"
  config.vm.box_url = "evansye/hadoocker-bigtop"

  config.vm.define "hadoop" do |node|
    node.vm.provider "virtualbox" do |vb|
      # Don't boot with headless mode
      vb.gui = false
      # Use VBoxManage to customize the VM. For example to change memory:
      vb.customize ["modifyvm", :id, "--memory", "1536"]
    end
    node.vm.hostname = "bigtop-hadoop.hadoocker"
    node.vm.provision "shell", inline: "/hadoop-init.sh", run: "always"
  end

end
