# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "evansye/hadoocker-base"

  config.vm.define "image" do |image|
    image.vm.hostname = "hadoocker-base.hadoocker"
  end

end
