# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # use vagrant-cachier to cache packages at local(https://github.com/fgrehm/vagrant-cachier)
  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
  end

  config.vm.box_download_insecure = true
  config.vm.box = "evansye/hadoocker-base"

  config.vm.define "image" do |image|
    image.vm.hostname = "hadoocker-base.hadoocker"
  end

end
